# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6b3d0ab8b0ccc15f3b827c57d9d584e9854b8675d064353a13584edaff29d3b75087ef79f67796ef1cadd787f7fc8b95876eec4da8d3b690b12bf9d4975fa25

test:
  secret_key_base: e989288e17bb039d6011cc6f2941a47bfd94a3a31eaf53dad46db736e2e0b0bfe3ab2188a3ad33120a21984e620103cae925f4729c4820328f7d5c5c3847f1b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
